
package "Adapter" as Adapter {

    class Dac {
        + sendBuffer(buffer)
    }

    class Button {
        + value readQueue()
        + bool getState(pin)
    }

    class Encoder {
        + value getvalue();
        + value getLastValue();
        + resetvalue();
        + changeExternalValue(...);
    }

    class Screen {
        + clear();
        + display();
        + drawBitmap(...);
        + drawPixel(...);
        + drawString(...);
        + drawNumber(...);
    }

    class Timer {
        + value getValue();
        + setValue(value);
    }

    class util {
        + time millis();
        + time micros();
        + void delay(ms);
    }
}
